version: '3.7'

services:
  tw-nginx:
    image: tw-nginx:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    labels:
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:tw-scripts.fichtme.nl
      - traefik.docker.network=web
      - traefik.docker.port=80
    expose:
      - 80
    networks:
      - web

networks:
  web:
    external: true
